plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'kotlin-kapt'
}

android {
    namespace 'com.todo.list'
    compileSdk 34

    defaultConfig {
        applicationId 'com.example.debug'
//        applicationId "com.sag.todo.list.task.reminder"

        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0.0"
        multiDexEnabled true

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"


        def appName = "To-Do-List-Task-Reminder"
        def versionCode = android.defaultConfig.versionCode.toString().trim()
        def versionName = android.defaultConfig.versionName
        setProperty("archivesBaseName", "$appName-VC-$versionCode-VN-$versionName")
    }

    buildTypes {
        release {

            resValue "string", "app_id", "ca-app-pub-3940256099942544~3347511713"
            resValue "string", "dashboard_banner_id", "ca-app-pub-3342111410257125/9943801959"

            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {

            resValue "string", "app_id", "ca-app-pub-3342111410257125~8073205135"
            resValue "string", "dashboard_banner_id", "ca-app-pub-3940256099942544/9214589741"
            
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    buildFeatures {
        viewBinding true
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'

//    'sdp' dependency...
    api 'com.intuit.sdp:sdp-android:1.1.1'

//    'ssp' dependency...
    api 'com.intuit.ssp:ssp-android:1.1.1'

//    'Toasty Toast' dependency...
    api 'com.github.GrenderG:Toasty:1.5.2'

//    'Lottie Animation' dependency...
    api 'com.airbnb.android:lottie:6.4.0'

//    'ViewModel & LiveData' dependency...
    implementation 'androidx.lifecycle:lifecycle-livedata-ktx:2.7.0'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.7.0'

//    'CircularImageView' dependency...
    api 'com.github.AtifSayings:CircularImageView:1.0.2'

//    'MultiDex' dependency...
    implementation "androidx.multidex:multidex:2.0.1"

//    'ShapeableImageView' dependency...
    api 'com.google.android.material:material:1.11.0'

//    'ROOM database' dependency...
    def room_version = "2.6.1"
    implementation "androidx.room:room-runtime:$room_version"
    annotationProcessor "androidx.room:room-compiler:$room_version"
    kapt "androidx.room:room-compiler:$room_version"

//    'Ads' dependency...
    api "com.google.android.gms:play-services-ads:23.0.0"
}